# Page settings
baseurl = "localhost:1313"
title = "Cassie & Devon"
languageCode = "en-us"
theme = "elate"
publishDir = "docs"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Devon Finninger"
  description = "Wedding Page"
  email = "fwd.finninger@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Cassie & Devon"
    home = "Home"
    work = "Engagement"
    testimonials = "Testimonials"
    services = "Wedding"
    about = "About Us"
    contact = "Contact Us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "https://goo.gl/forms/8PgiejaQV38pTCPG2"
    #  name = "RSVP"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "External link"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "Cassie's & Devon's Wedding"
    subtitle = "A bitchin' shindig with tons of booze and just about everything else awesome you can think of. Like even more stuff that you can imagine - hookers and blackjack don't even begin to describe what awesome things await within!"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Venue"
    description = "This place is super wet and awesome and you may need an umbrella, hence the neat-o icon you see there."
    url = "http://www.oregon.gov/pages/index.aspx"
    button = "Find Serenity"
    icon = "icon-umbrella"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Registry"
    description = "Please feel free to buy us anything that you see on here because it is super awesome!! If you have the option of shipping it directly to our home, then that would be preferable!"
    url = "https://amazon.com"
    button = "Buy us stuff!"
    icon = "icon-present"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Social"
    description = "Sam? SAAAAAAMMMMMM!!!"
    url = "https://www.instagram.com/explore/tags/findingfrodo/"
    button = "#FindingFrodo"
    icon = "icon-social-instagram"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Click Here for the Proposal Video!"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


  # Work section
  [params.work]
    enable = true
    title = "Engagement"
    description = "We got engaged in The Garden of the Gods near Colorado Springs during our fifth anniversary vacation."
    footertext = 'placeholder text'

    [[params.work.row]]
      img = "prop_1.jpg"
      alt = "Garden of the Gods"
      title = "Looking Out"
      subtitle = "Our view during the proposal"

    [[params.work.row]]
      img = "prop_2.jpg"
      alt = "During the Proposal"
      title = "Surprise Photo!"
      subtitle = "Someone was able to take some pictures"

    [[params.work.row]]
      img = "prop_3.jpg"
      alt = "View from the Mountain"
      title = "From the Broadmoor Cloud Camp"
      subtitle = "Our view of GotG from our cabin that night"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Some people have great things to say about our relationship! Secret voice recodings have been transcribed here!"

    [[params.testimonials.item]]
      quote = "&ldquo;AAAHHHHH!! So excited. I mean, Cassie is amazing and wonderful and beautiful and Devon's kinda cool too.&rdquo;"
      person = 'Melody Young, Software Engineer <span class="subtext">Friend for Life</span>'
      img = "people_mel_jeff.jpg"
      alt = "Melody Young"

    [[params.testimonials.item]]
      quote = "&ldquo;These people are superior beings.&rdquo;"
      person = 'Haley Brenna, Medical Assistant <span class="subtext">Friend for Life</span>'
      img = "people_haley.jpg"
      alt = "Haley Brenna"

    [[params.testimonials.item]]
      quote = "&ldquo;They are not throwing away their shot.&rdquo;"
      person = 'Alexander Hamilton, Bastard, Orphan, Son of a Whore and a Scotsman <span class="subtext">Hero and a Scholar</span>'
      img = "people_alex_hamilton.jpg"
      alt = "Alexander Hamilton"
  
  # Services section
  [params.services]
    enable = true
    title = "Extra Wedding Information"
    description = "Things you should know before attending"

    [[params.services.item]]
      title = "Food Preference and Allergies"
      description = "Gluten-free and vegetarian options will be provided upon request! Please make sure to fill out the corresponding field on the RSVP form so that we can get an accurate count."
      icon = "icon-user"

    [[params.services.item]]
      title = "Travel & Accommodations"
      description = "No day-of shuttles will be provided. Please find your own transportation to the venue. We will have Hotel blocks - details TBD."
      icon = "icon-compass"

    [[params.services.item]]
      title = "RSVP Deadlines"
      description = "In order for us to accurately plan out our wedding ceremony, RSVPs will need to be completed by {{ $wedding_date - 3*Time.months | date }}."
      icon = "icon-calendar"

      [[params.services.item]]
      title = "Wedding Registry"
      description = "Our wedding registry is all online, where you can have it shipped to our home. Our wedding is out of state and it will be difficult for us to ship everything back, so please send the items directly to our home and simply bring a crad to the wedding if you so choose."      
      icon = "icon-envelope"

  # About section
  [params.about]
    enable = true
    title = "About Us"
    description = "About us as a couple and individuals."

    [[params.about.item]]
      name = "Cassie Anderson"
      position = "Bride"
      description = "she's pretty good"
      img = "people_cassie.jpg"
      alt = "Cassie"
      social = []

    [[params.about.item]]
      name = "Cora"
      position = "Best Puppy"
      description = "I cannot describe this puppy, you just need to spend time with her. She's the best AROUND. Never gonna let you down.'"
      img = "people_cora.jpg"
      alt = "Cora"
      social = []

    [[params.about.item]]
      name = "Devon Finninger"
      position = "Groom"
      description = "This dude is HAWT. Good LAWDY."
      img = "people_devon.jpg"
      alt = "Devon"
      social = []      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Our Days Together"
      icon = "icon-people"
      from = 0
      to = 2561
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "Venues Researched"
      icon = "icon-magnifier"
      from = 0
      to = 18
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "States Inhabited"
      icon = "icon-map"
      from = 0
      to = 3
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "RSVPs Received"
      icon = "icon-envelope-letter"
      from = 0
      to = 52
      interval = 50
      speed = 3000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Contact Us!"
    description = "If you have questions regarding the wedding, drop us a line here and we'll both get a copy."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "3932 Colegrove St., San Mateo, California, 94403"],
        ["icon-envelope", "fwd.finninger@gmail.com"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message" 

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
